// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Watchtower.Application.Persistence;

#nullable disable

namespace Watchtower.Application.Persistence.Migrations
{
    [DbContext(typeof(WatchtowerDbContext))]
    [Migration("20260825120402_AddProductCiRepo")]
    partial class AddProductCiRepo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elarion.Coordination.PostgreSql.RoleLeaseEntity", b =>
                {
                    b.Property<string>("Role")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("role");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner");

                    b.HasKey("Role")
                        .HasName("pk_elarion_role_leases");

                    b.ToTable("elarion_role_leases", (string)null);
                });

            modelBuilder.Entity("Elarion.Scheduling.EntityFrameworkCore.SchedulerClaimEntity", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("job_name");

                    b.Property<DateTimeOffset>("OccurrenceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_utc");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.HasKey("JobName", "OccurrenceUtc")
                        .HasName("pk_elarion_scheduler_claims");

                    b.HasIndex("OccurrenceUtc")
                        .HasDatabaseName("ix_elarion_scheduler_claims_purge");

                    b.ToTable("elarion_scheduler_claims", (string)null);
                });

            modelBuilder.Entity("Elarion.Settings.EntityFrameworkCore.Setting", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Owner")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("owner");

                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Kind", "Owner", "Key")
                        .HasName("pk_elarion_settings");

                    b.ToTable("elarion_settings", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.AcmeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountUrl")
                        .HasColumnType("text")
                        .HasColumnName("account_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DirectoryUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("directory_url");

                    b.Property<byte[]>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("private_key");

                    b.Property<string>("Protection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protection");

                    b.HasKey("Id")
                        .HasName("pk_acme_accounts");

                    b.HasIndex("DirectoryUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_acme_accounts_directory_url");

                    b.ToTable("acme_accounts", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.AcmeHttpChallenge", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("KeyAuthorization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_authorization");

                    b.HasKey("Token")
                        .HasName("pk_acme_http_challenges");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_acme_http_challenges_expires_at");

                    b.ToTable("acme_http_challenges", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_audit_events_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_events_created_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.AuthSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_expires_at");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_auth_sessions_route_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_sessions_user_id");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.BackupEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<string>("RemotePath")
                        .HasColumnType("text")
                        .HasColumnName("remote_path");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("StackId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_backup_events");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_backup_events_status");

                    b.HasIndex("StackId", "StartedAt")
                        .HasDatabaseName("ix_backup_events_stack_id_started_at");

                    b.ToTable("backup_events", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.BackupPausedContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("container_id");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("container_name");

                    b.Property<DateTimeOffset>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stack_name");

                    b.HasKey("Id")
                        .HasName("pk_backup_paused_containers");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_backup_paused_containers_container_id");

                    b.ToTable("backup_paused_containers", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.CiRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDockerSocket")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_docker_socket");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CredentialId")
                        .HasColumnType("integer")
                        .HasColumnName("credential_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("ExtraLabels")
                        .HasColumnType("text")
                        .HasColumnName("extra_labels");

                    b.Property<string>("LastRegistrySyncError")
                        .HasColumnType("text")
                        .HasColumnName("last_registry_sync_error");

                    b.Property<string>("LastWarmError")
                        .HasColumnType("text")
                        .HasColumnName("last_warm_error");

                    b.Property<DateTimeOffset?>("LastWarmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_warmed_at");

                    b.Property<int>("MaxConcurrentRunners")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_runners");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner");

                    b.Property<DateTimeOffset?>("RegistrySyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registry_synced_at");

                    b.Property<string>("RegistrySyncedHash")
                        .HasColumnType("text")
                        .HasColumnName("registry_synced_hash");

                    b.Property<string>("RunnerImage")
                        .HasColumnType("text")
                        .HasColumnName("runner_image");

                    b.Property<string>("SyncRegistryUrl")
                        .HasColumnType("text")
                        .HasColumnName("sync_registry_url");

                    b.Property<DateTimeOffset?>("ToolchainDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("toolchain_detected_at");

                    b.Property<string>("ToolchainProfileJson")
                        .HasColumnType("text")
                        .HasColumnName("toolchain_profile_json");

                    b.Property<string>("WarmedProfileHash")
                        .HasColumnType("text")
                        .HasColumnName("warmed_profile_hash");

                    b.HasKey("Id")
                        .HasName("pk_ci_repos");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_ci_repos_credential_id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ci_repos_owner_name");

                    b.ToTable("ci_repos", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_credentials_name");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.DeployEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Output")
                        .HasColumnType("text")
                        .HasColumnName("output");

                    b.Property<int>("StackId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_deploy_events");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deploy_events_status");

                    b.HasIndex("StackId", "StartedAt")
                        .HasDatabaseName("ix_deploy_events_stack_id_started_at");

                    b.ToTable("deploy_events", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.Property<int>("RealmId")
                        .HasColumnType("integer")
                        .HasColumnName("realm_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("RealmId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_realm_id_normalized_name");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_group_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user_id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_members_group_id_user_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.LoginCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redirect_uri");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login_codes");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_login_codes_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_login_codes_expires_at");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_login_codes_route_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_codes_user_id");

                    b.ToTable("login_codes", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.MetricContainerSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("container_name");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_percent");

                    b.Property<long?>("MemLimitBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("mem_limit_bytes");

                    b.Property<long>("MemUsedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("mem_used_bytes");

                    b.Property<string>("StackName")
                        .HasColumnType("text")
                        .HasColumnName("stack_name");

                    b.Property<long>("TUnixSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("t_unix_seconds");

                    b.Property<int>("TierSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("tier_seconds");

                    b.HasKey("Id")
                        .HasName("pk_metric_container_samples");

                    b.HasIndex("TierSeconds", "TUnixSeconds", "ContainerName")
                        .IsUnique()
                        .HasDatabaseName("ix_metric_container_samples_tier_seconds_t_unix_seconds_contai");

                    b.ToTable("metric_container_samples", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.MetricHostSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("CpuPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_percent");

                    b.Property<double?>("LoadAvg1")
                        .HasColumnType("double precision")
                        .HasColumnName("load_avg1");

                    b.Property<double?>("LoadAvg5")
                        .HasColumnType("double precision")
                        .HasColumnName("load_avg5");

                    b.Property<double?>("MemPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("mem_percent");

                    b.Property<long?>("MemUsedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("mem_used_bytes");

                    b.Property<long>("TUnixSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("t_unix_seconds");

                    b.Property<int>("TierSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("tier_seconds");

                    b.HasKey("Id")
                        .HasName("pk_metric_host_samples");

                    b.HasIndex("TierSeconds", "TUnixSeconds")
                        .IsUnique()
                        .HasDatabaseName("ix_metric_host_samples_tier_seconds_t_unix_seconds");

                    b.ToTable("metric_host_samples", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CiRepoId")
                        .HasColumnType("integer")
                        .HasColumnName("ci_repo_id");

                    b.Property<string>("ComposeFilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compose_file_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CredentialId")
                        .HasColumnType("integer")
                        .HasColumnName("credential_id");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_branch");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repository_url");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CiRepoId")
                        .HasDatabaseName("ix_products_ci_repo_id");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_products_credential_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.ProxyCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificatePem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certificate_pem");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset>("NotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_after");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("not_before");

                    b.Property<byte[]>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("private_key");

                    b.Property<string>("Protection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protection");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbprint");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_proxy_certificates");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_proxy_certificates_host");

                    b.ToTable("proxy_certificates", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Realm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<int?>("LoginRouteId")
                        .HasColumnType("integer")
                        .HasColumnName("login_route_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_realms");

                    b.HasIndex("LoginRouteId")
                        .IsUnique()
                        .HasDatabaseName("ix_realms_login_route_id")
                        .HasFilter("\"login_route_id\" IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_realms_slug");

                    b.ToTable("realms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystem = true,
                            Name = "Operator",
                            Slug = "operator"
                        });
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Registry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CredentialId")
                        .HasColumnType("integer")
                        .HasColumnName("credential_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_registries");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_registries_credential_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_registries_name");

                    b.ToTable("registries", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Public")
                        .HasColumnName("access_mode");

                    b.Property<string>("BypassPaths")
                        .HasColumnType("text")
                        .HasColumnName("bypass_paths");

                    b.Property<DateTimeOffset?>("CertNotAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cert_not_after");

                    b.Property<int>("ContainerPort")
                        .HasColumnType("integer")
                        .HasColumnName("container_port");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("IdentityHeaderMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None")
                        .HasColumnName("identity_header_mode");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int?>("RealmId")
                        .HasColumnType("integer")
                        .HasColumnName("realm_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.Property<int?>("StackId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("text")
                        .HasColumnName("status_detail");

                    b.Property<string>("Target")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Service")
                        .HasColumnName("target");

                    b.Property<bool>("TlsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("tls_enabled");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_routes_domain");

                    b.HasIndex("RealmId")
                        .HasDatabaseName("ix_routes_realm_id");

                    b.HasIndex("StackId")
                        .HasDatabaseName("ix_routes_stack_id");

                    b.ToTable("routes", null, t =>
                        {
                            t.HasCheckConstraint("ck_routes_target", "(\"target\" = 'Watchtower' AND \"stack_id\" IS NULL AND \"realm_id\" IS NOT NULL AND \"access_mode\" = 'Public')\nOR (\"target\" = 'Service' AND \"stack_id\" IS NOT NULL AND \"realm_id\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Watchtower.Application.Entities.RouteAccessGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_route_access_grants");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_route_access_grants_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_route_access_grants_user_id");

                    b.HasIndex("RouteId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_route_access_grants_route_id_group_id")
                        .HasFilter("\"group_id\" IS NOT NULL");

                    b.HasIndex("RouteId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_route_access_grants_route_id_user_id")
                        .HasFilter("\"user_id\" IS NOT NULL");

                    b.ToTable("route_access_grants", null, t =>
                        {
                            t.HasCheckConstraint("ck_route_access_grants_subject", "(\"user_id\" IS NOT NULL) <> (\"group_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Watchtower.Application.Entities.SigningKey", b =>
                {
                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<byte[]>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("private_key");

                    b.Property<string>("Protection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protection");

                    b.HasKey("Purpose")
                        .HasName("pk_signing_keys");

                    b.ToTable("signing_keys", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AppApiEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("app_api_enabled");

                    b.Property<string>("AppApiToken")
                        .HasColumnType("text")
                        .HasColumnName("app_api_token");

                    b.Property<string>("AutoDeployMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auto_deploy_mode");

                    b.Property<string>("AutoDeployTime")
                        .HasColumnType("text")
                        .HasColumnName("auto_deploy_time");

                    b.Property<string>("BackupCron")
                        .HasColumnType("text")
                        .HasColumnName("backup_cron");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("backup_enabled");

                    b.Property<string>("BackupQuiesceMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Stop")
                        .HasColumnName("backup_quiesce_mode");

                    b.Property<bool>("BackupStopContainers")
                        .HasColumnType("boolean")
                        .HasColumnName("backup_stop_containers");

                    b.Property<string>("BranchOverride")
                        .HasColumnType("text")
                        .HasColumnName("branch_override");

                    b.Property<string>("ComposeProjectName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compose_project_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DesiredState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Running")
                        .HasColumnName("desired_state");

                    b.Property<string>("LastDeployStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_deploy_status");

                    b.Property<DateTimeOffset?>("LastDeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_deployed_at");

                    b.Property<string>("LastDeployedCommit")
                        .HasColumnType("text")
                        .HasColumnName("last_deployed_commit");

                    b.Property<DateTimeOffset?>("LastScheduledBackupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scheduled_backup_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<string>("TenantSlug")
                        .HasColumnType("text")
                        .HasColumnName("tenant_slug");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("webhook_enabled");

                    b.Property<string>("WebhookToken")
                        .HasColumnType("text")
                        .HasColumnName("webhook_token");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_stacks");

                    b.HasIndex("AppApiToken")
                        .IsUnique()
                        .HasDatabaseName("ix_stacks_app_api_token");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stacks_name");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stacks_product_id");

                    b.HasIndex("TemplateId", "TenantSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_stacks_template_id_tenant_slug");

                    b.ToTable("stacks", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackBackupServiceOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dump")
                        .HasColumnType("text")
                        .HasColumnName("dump");

                    b.Property<bool>("Exclude")
                        .HasColumnType("boolean")
                        .HasColumnName("exclude");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service");

                    b.Property<int>("StackId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_id");

                    b.Property<string>("Stop")
                        .HasColumnType("text")
                        .HasColumnName("stop");

                    b.HasKey("Id")
                        .HasName("pk_stack_backup_service_overrides");

                    b.HasIndex("StackId", "Service")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_backup_service_overrides_stack_id_service");

                    b.ToTable("stack_backup_service_overrides", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackEnvVar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("StackId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_stack_env_vars");

                    b.HasIndex("StackId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_env_vars_stack_id_key");

                    b.ToTable("stack_env_vars", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchOverride")
                        .HasColumnType("text")
                        .HasColumnName("branch_override");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DomainPattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("RealmId")
                        .HasColumnType("integer")
                        .HasColumnName("realm_id");

                    b.Property<int>("TargetPort")
                        .HasColumnType("integer")
                        .HasColumnName("target_port");

                    b.Property<string>("TargetServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_service_name");

                    b.HasKey("Id")
                        .HasName("pk_stack_templates");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_templates_name");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stack_templates_product_id");

                    b.HasIndex("RealmId")
                        .HasDatabaseName("ix_stack_templates_realm_id");

                    b.ToTable("stack_templates", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplateEnvVar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_stack_template_env_vars");

                    b.HasIndex("TemplateId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_template_env_vars_template_id_key");

                    b.ToTable("stack_template_env_vars", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackUpdateCheck", b =>
                {
                    b.Property<int>("StackId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<bool>("HasUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("has_updates");

                    b.Property<string>("NewCommitSha")
                        .HasColumnType("text")
                        .HasColumnName("new_commit_sha");

                    b.Property<string>("OutdatedImageDigests")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outdated_image_digests");

                    b.Property<string>("OutdatedImages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outdated_images");

                    b.HasKey("StackId")
                        .HasName("pk_stack_update_checks");

                    b.ToTable("stack_update_checks", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.TemplateManagementGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_delete");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("StackId")
                        .HasColumnType("integer")
                        .HasColumnName("stack_id");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_management_grants");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_template_management_grants_template_id");

                    b.HasIndex("StackId", "TemplateId")
                        .IsUnique()
                        .HasDatabaseName("ix_template_management_grants_stack_id_template_id");

                    b.ToTable("template_management_grants", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AuthenticatorKey")
                        .HasColumnType("text")
                        .HasColumnName("authenticator_key");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("RealmId")
                        .HasColumnType("integer")
                        .HasColumnName("realm_id");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RealmId", "NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_realm_id_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.UserRecoveryCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_recovery_codes");

                    b.HasIndex("UserId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_recovery_codes_user_id_code_hash");

                    b.ToTable("user_recovery_codes", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.AuthSession", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_auth_sessions_routes_route_id");

                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.BackupEvent", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backup_events_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.CiRepo", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ci_repos_credentials_credential_id");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.DeployEvent", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany("DeployEvents")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deploy_events_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Group", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_realms_realm_id");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.GroupMember", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.LoginCode", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_codes_routes_route_id");

                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_codes_users_user_id");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Product", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.CiRepo", "CiRepo")
                        .WithMany()
                        .HasForeignKey("CiRepoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_products_ci_repos_ci_repo_id");

                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_products_credentials_credential_id");

                    b.Navigation("CiRepo");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Realm", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Route", "LoginRoute")
                        .WithMany()
                        .HasForeignKey("LoginRouteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_realms_routes_login_route_id");

                    b.Navigation("LoginRoute");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Registry", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_registries_credentials_credential_id");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Route", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_routes_realms_realm_id");

                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_routes_stacks_stack_id");

                    b.Navigation("Realm");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.RouteAccessGrant", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_route_access_grants_groups_group_id");

                    b.HasOne("Watchtower.Application.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_access_grants_routes_route_id");

                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_route_access_grants_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Product", "Product")
                        .WithMany("Stacks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stacks_products_product_id");

                    b.HasOne("Watchtower.Application.Entities.StackTemplate", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stacks_stack_templates_template_id");

                    b.Navigation("Product");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackBackupServiceOverride", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_backup_service_overrides_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackEnvVar", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany("EnvVars")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_env_vars_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplate", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Product", "Product")
                        .WithMany("Templates")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stack_templates_products_product_id");

                    b.HasOne("Watchtower.Application.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stack_templates_realms_realm_id");

                    b.Navigation("Product");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplateEnvVar", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.StackTemplate", "Template")
                        .WithMany("BaseEnvVars")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_template_env_vars_stack_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackUpdateCheck", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithOne("UpdateCheck")
                        .HasForeignKey("Watchtower.Application.Entities.StackUpdateCheck", "StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_update_checks_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.TemplateManagementGrant", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_management_grants_stacks_stack_id");

                    b.HasOne("Watchtower.Application.Entities.StackTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_management_grants_stack_templates_template_id");

                    b.Navigation("Stack");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.User", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_realms_realm_id");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.UserRecoveryCode", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_recovery_codes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Product", b =>
                {
                    b.Navigation("Stacks");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.Navigation("DeployEvents");

                    b.Navigation("EnvVars");

                    b.Navigation("UpdateCheck");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplate", b =>
                {
                    b.Navigation("BaseEnvVars");

                    b.Navigation("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
