// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Watchtower.Application.Persistence;

#nullable disable

namespace Watchtower.Application.Persistence.Migrations
{
    [DbContext(typeof(WatchtowerDbContext))]
    [Migration("20260821204635_UnifyAuditTrail")]
    partial class UnifyAuditTrail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Elarion.Settings.EntityFrameworkCore.Setting", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Owner")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_on_utc");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Kind", "Owner", "Key")
                        .HasName("pk_elarion_settings");

                    b.ToTable("elarion_settings", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_audit_events_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_events_created_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.AuthSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<int?>("RouteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("route_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_expires_at");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_auth_sessions_route_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_sessions_user_id");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.BackupEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT")
                        .HasColumnName("output");

                    b.Property<string>("RemotePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_path");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_backup_events");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_backup_events_status");

                    b.HasIndex("StackId", "StartedAt")
                        .HasDatabaseName("ix_backup_events_stack_id_started_at");

                    b.ToTable("backup_events", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.CiRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AllowDockerSocket")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_docker_socket");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CredentialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credential_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("ExtraLabels")
                        .HasColumnType("TEXT")
                        .HasColumnName("extra_labels");

                    b.Property<string>("LastWarmError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_warm_error");

                    b.Property<DateTimeOffset?>("LastWarmedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_warmed_at");

                    b.Property<int>("MaxConcurrentRunners")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_concurrent_runners");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<string>("RunnerImage")
                        .HasColumnType("TEXT")
                        .HasColumnName("runner_image");

                    b.Property<DateTimeOffset?>("ToolchainDetectedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("toolchain_detected_at");

                    b.Property<string>("ToolchainProfileJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("toolchain_profile_json");

                    b.Property<string>("WarmedProfileHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("warmed_profile_hash");

                    b.HasKey("Id")
                        .HasName("pk_ci_repos");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_ci_repos_credential_id");

                    b.HasIndex("Owner", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ci_repos_owner_name");

                    b.ToTable("ci_repos", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_credentials_name");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.DeployEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT")
                        .HasColumnName("output");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_deploy_events");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deploy_events_status");

                    b.HasIndex("StackId", "StartedAt")
                        .HasDatabaseName("ix_deploy_events_stack_id_started_at");

                    b.ToTable("deploy_events", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_name");

                    b.Property<int>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realm_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("RealmId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_realm_id_normalized_name");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_group_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user_id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_group_members_group_id_user_id");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.LoginCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("redirect_uri");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("route_id");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login_codes");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_login_codes_code_hash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_login_codes_expires_at");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("ix_login_codes_route_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_codes_user_id");

                    b.ToTable("login_codes", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.MetricContainerSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("container_name");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("cpu_percent");

                    b.Property<long?>("MemLimitBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mem_limit_bytes");

                    b.Property<long>("MemUsedBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mem_used_bytes");

                    b.Property<string>("StackName")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_name");

                    b.Property<long>("TUnixSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("t_unix_seconds");

                    b.Property<int>("TierSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tier_seconds");

                    b.HasKey("Id")
                        .HasName("pk_metric_container_samples");

                    b.HasIndex("TierSeconds", "TUnixSeconds", "ContainerName")
                        .IsUnique()
                        .HasDatabaseName("ix_metric_container_samples_tier_seconds_t_unix_seconds_container_name");

                    b.ToTable("metric_container_samples", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.MetricHostSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double?>("CpuPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("cpu_percent");

                    b.Property<double?>("LoadAvg1")
                        .HasColumnType("REAL")
                        .HasColumnName("load_avg1");

                    b.Property<double?>("LoadAvg5")
                        .HasColumnType("REAL")
                        .HasColumnName("load_avg5");

                    b.Property<double?>("MemPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("mem_percent");

                    b.Property<long?>("MemUsedBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mem_used_bytes");

                    b.Property<long>("TUnixSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("t_unix_seconds");

                    b.Property<int>("TierSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tier_seconds");

                    b.HasKey("Id")
                        .HasName("pk_metric_host_samples");

                    b.HasIndex("TierSeconds", "TUnixSeconds")
                        .IsUnique()
                        .HasDatabaseName("ix_metric_host_samples_tier_seconds_t_unix_seconds");

                    b.ToTable("metric_host_samples", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Realm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthHost")
                        .HasColumnType("TEXT")
                        .HasColumnName("auth_host");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_realms");

                    b.HasIndex("AuthHost")
                        .IsUnique()
                        .HasDatabaseName("ix_realms_auth_host")
                        .HasFilter("\"auth_host\" IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_realms_slug");

                    b.ToTable("realms", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Registry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CredentialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credential_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_registries");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_registries_credential_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_registries_name");

                    b.ToTable("registries", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("access_mode");

                    b.Property<string>("BypassPaths")
                        .HasColumnType("TEXT")
                        .HasColumnName("bypass_paths");

                    b.Property<DateTimeOffset?>("CertNotAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("cert_not_after");

                    b.Property<int>("ContainerPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("container_port");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("domain");

                    b.Property<string>("IdentityHeaderMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("identity_header_mode");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("service_name");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StatusDetail")
                        .HasColumnType("TEXT")
                        .HasColumnName("status_detail");

                    b.Property<bool>("TlsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tls_enabled");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("ix_routes_domain");

                    b.HasIndex("StackId")
                        .HasDatabaseName("ix_routes_stack_id");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.RouteAccessGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("route_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_route_access_grants");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_route_access_grants_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_route_access_grants_user_id");

                    b.HasIndex("RouteId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_route_access_grants_route_id_group_id")
                        .HasFilter("\"group_id\" IS NOT NULL");

                    b.HasIndex("RouteId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_route_access_grants_route_id_user_id")
                        .HasFilter("\"user_id\" IS NOT NULL");

                    b.ToTable("route_access_grants", null, t =>
                        {
                            t.HasCheckConstraint("ck_route_access_grants_subject", "(\"user_id\" IS NOT NULL) <> (\"group_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AppApiEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("app_api_enabled");

                    b.Property<string>("AppApiToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_api_token");

                    b.Property<string>("AutoDeployMode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auto_deploy_mode");

                    b.Property<string>("AutoDeployTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("auto_deploy_time");

                    b.Property<bool>("BackupEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("backup_enabled");

                    b.Property<bool>("BackupStopContainers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("backup_stop_containers");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<string>("ComposeFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compose_file_path");

                    b.Property<string>("ComposeProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compose_project_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CredentialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credential_id");

                    b.Property<string>("LastDeployStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_deploy_status");

                    b.Property<DateTimeOffset?>("LastDeployedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_deployed_at");

                    b.Property<string>("LastDeployedCommit")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_deployed_commit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_url");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_id");

                    b.Property<string>("TenantSlug")
                        .HasColumnType("TEXT")
                        .HasColumnName("tenant_slug");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("webhook_enabled");

                    b.Property<string>("WebhookToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("webhook_token");

                    b.HasKey("Id")
                        .HasName("pk_stacks");

                    b.HasIndex("AppApiToken")
                        .IsUnique()
                        .HasDatabaseName("ix_stacks_app_api_token");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_stacks_credential_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stacks_name");

                    b.HasIndex("TemplateId", "TenantSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_stacks_template_id_tenant_slug");

                    b.ToTable("stacks", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackEnvVar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_stack_env_vars");

                    b.HasIndex("StackId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_env_vars_stack_id_key");

                    b.ToTable("stack_env_vars", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<string>("ComposeFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compose_file_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CredentialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credential_id");

                    b.Property<string>("DomainPattern")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("domain_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realm_id");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_url");

                    b.Property<int>("TargetPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_port");

                    b.Property<string>("TargetServiceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_service_name");

                    b.HasKey("Id")
                        .HasName("pk_stack_templates");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_stack_templates_credential_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_templates_name");

                    b.HasIndex("RealmId")
                        .HasDatabaseName("ix_stack_templates_realm_id");

                    b.ToTable("stack_templates", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplateEnvVar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_stack_template_env_vars");

                    b.HasIndex("TemplateId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_template_env_vars_template_id_key");

                    b.ToTable("stack_template_env_vars", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackUpdateCheck", b =>
                {
                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("checked_at");

                    b.Property<bool>("HasUpdates")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_updates");

                    b.Property<string>("NewCommitSha")
                        .HasColumnType("TEXT")
                        .HasColumnName("new_commit_sha");

                    b.Property<string>("OutdatedImageDigests")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outdated_image_digests");

                    b.Property<string>("OutdatedImages")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outdated_images");

                    b.HasKey("StackId")
                        .HasName("pk_stack_update_checks");

                    b.ToTable("stack_update_checks", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.TemplateManagementGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AllowDelete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("allow_delete");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_management_grants");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_template_management_grants_template_id");

                    b.HasIndex("StackId", "TemplateId")
                        .IsUnique()
                        .HasDatabaseName("ix_template_management_grants_stack_id_template_id");

                    b.ToTable("template_management_grants", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AuthenticatorKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("authenticator_key");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("RealmId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realm_id");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RealmId", "NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_realm_id_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.UserRecoveryCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_recovery_codes");

                    b.HasIndex("UserId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_recovery_codes_user_id_code_hash");

                    b.ToTable("user_recovery_codes", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.AuthSession", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_auth_sessions_routes_route_id");

                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.BackupEvent", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_backup_events_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.CiRepo", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ci_repos_credentials_credential_id");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.DeployEvent", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany("DeployEvents")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deploy_events_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Group", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_realms_realm_id");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.GroupMember", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.LoginCode", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_codes_routes_route_id");

                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_codes_users_user_id");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Registry", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_registries_credentials_credential_id");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Route", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_routes_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.RouteAccessGrant", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_route_access_grants_groups_group_id");

                    b.HasOne("Watchtower.Application.Entities.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_route_access_grants_routes_route_id");

                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_route_access_grants_users_user_id");

                    b.Navigation("Group");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stacks_credentials_credential_id");

                    b.HasOne("Watchtower.Application.Entities.StackTemplate", "Template")
                        .WithMany("Instances")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stacks_stack_templates_template_id");

                    b.Navigation("Credential");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackEnvVar", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany("EnvVars")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_env_vars_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplate", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stack_templates_credentials_credential_id");

                    b.HasOne("Watchtower.Application.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stack_templates_realms_realm_id");

                    b.Navigation("Credential");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplateEnvVar", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.StackTemplate", "Template")
                        .WithMany("BaseEnvVars")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_template_env_vars_stack_templates_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackUpdateCheck", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithOne("UpdateCheck")
                        .HasForeignKey("Watchtower.Application.Entities.StackUpdateCheck", "StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_update_checks_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.TemplateManagementGrant", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany()
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_management_grants_stacks_stack_id");

                    b.HasOne("Watchtower.Application.Entities.StackTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_management_grants_stack_templates_template_id");

                    b.Navigation("Stack");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.User", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Realm", "Realm")
                        .WithMany()
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_realms_realm_id");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.UserRecoveryCode", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_recovery_codes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.Navigation("DeployEvents");

                    b.Navigation("EnvVars");

                    b.Navigation("UpdateCheck");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackTemplate", b =>
                {
                    b.Navigation("BaseEnvVars");

                    b.Navigation("Instances");
                });
#pragma warning restore 612, 618
        }
    }
}
