// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Watchtower.Application.Persistence;

#nullable disable

namespace Watchtower.Application.Persistence.Migrations
{
    [DbContext(typeof(WatchtowerDbContext))]
    partial class WatchtowerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Elarion.Settings.EntityFrameworkCore.Setting", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Owner")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedOnUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_on_utc");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Kind", "Owner", "Key")
                        .HasName("pk_elarion_settings");

                    b.ToTable("elarion_settings", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_credentials_name");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.DeployEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_at");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT")
                        .HasColumnName("output");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_deploy_events");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deploy_events_status");

                    b.HasIndex("StackId", "StartedAt")
                        .HasDatabaseName("ix_deploy_events_stack_id_started_at");

                    b.ToTable("deploy_events", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Registry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CredentialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credential_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_registries");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_registries_credential_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_registries_name");

                    b.ToTable("registries", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<string>("ComposeFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compose_file_path");

                    b.Property<string>("ComposeProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compose_project_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CredentialId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credential_id");

                    b.Property<string>("LastDeployStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_deploy_status");

                    b.Property<DateTimeOffset?>("LastDeployedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_deployed_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("repository_url");

                    b.Property<bool>("WebhookEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("webhook_enabled");

                    b.Property<string>("WebhookToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("webhook_token");

                    b.HasKey("Id")
                        .HasName("pk_stacks");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_stacks_credential_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_stacks_name");

                    b.ToTable("stacks", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackEnvVar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_stack_env_vars");

                    b.HasIndex("StackId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_stack_env_vars_stack_id_key");

                    b.ToTable("stack_env_vars", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackUpdateCheck", b =>
                {
                    b.Property<int>("StackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stack_id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("checked_at");

                    b.Property<bool>("HasUpdates")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_updates");

                    b.Property<string>("OutdatedImages")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outdated_images");

                    b.HasKey("StackId")
                        .HasName("pk_stack_update_checks");

                    b.ToTable("stack_update_checks", (string)null);
                });

            modelBuilder.Entity("Watchtower.Application.Entities.DeployEvent", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany("DeployEvents")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deploy_events_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Registry", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_registries_credentials_credential_id");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Credential", "Credential")
                        .WithMany()
                        .HasForeignKey("CredentialId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stacks_credentials_credential_id");

                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackEnvVar", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithMany("EnvVars")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_env_vars_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.StackUpdateCheck", b =>
                {
                    b.HasOne("Watchtower.Application.Entities.Stack", "Stack")
                        .WithOne("UpdateCheck")
                        .HasForeignKey("Watchtower.Application.Entities.StackUpdateCheck", "StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stack_update_checks_stacks_stack_id");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("Watchtower.Application.Entities.Stack", b =>
                {
                    b.Navigation("DeployEvents");

                    b.Navigation("EnvVars");

                    b.Navigation("UpdateCheck");
                });
#pragma warning restore 612, 618
        }
    }
}
