using Watchtower.Application.Services;
using Xunit;

namespace Watchtower.Application.Tests;

/// <summary>
/// The generated buildkitd.default.toml is what every consuming repo's
/// <c>docker/setup-buildx-action</c> silently inherits, so its shape is contract: registry stanzas
/// for exactly the daemon's insecure registries, an optional snapshotter override, and nothing a
/// hostile value could turn into TOML of its own.
/// </summary>
public sealed class CiBuildkitConfigTests {

    [Fact]
    public void Build_EmitsARegistryStanzaPerInsecureRegistry() {
        var toml = CiBuildkitConfig.Build(["simondatastore:50000", "10.0.0.5:5000"], snapshotter: null);

        Assert.Contains("[registry.\"simondatastore:50000\"]\n  http = true\n  insecure = true\n", toml);
        Assert.Contains("[registry.\"10.0.0.5:5000\"]", toml);
        Assert.DoesNotContain("[worker.oci]", toml);
    }

    [Fact]
    public void Build_EmitsTheSnapshotterOverride() {
        var toml = CiBuildkitConfig.Build([], "fuse-overlayfs");

        Assert.Contains("[worker.oci]\n  snapshotter = \"fuse-overlayfs\"\n", toml);
    }

    [Fact]
    public void Build_WithNothingToConfigure_StillReturnsTheHeaderOnlyFile() {
        var toml = CiBuildkitConfig.Build([], snapshotter: null);

        // Always a file: an emptied configuration must overwrite a stale one on the volume.
        Assert.StartsWith("# Generated by Watchtower", toml);
        Assert.DoesNotContain("[", toml);
    }

    /// <summary>
    /// Registry names reach this from the daemon's own config, but a value that cannot be a
    /// registry host must not be emitted into a quoted TOML string.
    /// </summary>
    [Theory]
    [InlineData("bad\"host")]
    [InlineData("bad host")]
    [InlineData("bad\\host")]
    [InlineData("host\"]\n[worker.oci")]
    public void Build_SkipsRegistryNamesThatCannotBeHosts(string name) {
        var toml = CiBuildkitConfig.Build([name, "good:5000"], snapshotter: null);

        Assert.Contains("[registry.\"good:5000\"]", toml);
        Assert.Single(toml.Split("[registry."), s => s.StartsWith('"'));
    }

    [Fact]
    public void Build_RefusesAnInvalidSnapshotterInsteadOfEmittingBrokenToml() =>
        Assert.Throws<ArgumentException>(() => CiBuildkitConfig.Build([], "no\"quotes"));

    [Theory]
    [InlineData("native", true)]
    [InlineData("overlayfs", true)]
    [InlineData("fuse-overlayfs", true)]
    [InlineData("stargz", true)]
    [InlineData("", false)]
    [InlineData("Fuse-Overlayfs", false)]
    [InlineData("a b", false)]
    [InlineData("x\"y", false)]
    public void IsValidSnapshotter_AcceptsSnapshotterNamesOnly(string value, bool valid) =>
        Assert.Equal(valid, CiBuildkitConfig.IsValidSnapshotter(value));

    [Fact]
    public void Build_IsStableForTheSameInputsRegardlessOfOrder() {
        var a = CiBuildkitConfig.Build(["b:1", "a:1"], "native");
        var b = CiBuildkitConfig.Build(["a:1", "b:1"], "native");

        Assert.Equal(a, b);
        Assert.Equal(CiBuildkitConfig.Stamp(a), CiBuildkitConfig.Stamp(b));
    }

    [Fact]
    public void Stamp_ChangesWithTheContent() =>
        Assert.NotEqual(
            CiBuildkitConfig.Stamp(CiBuildkitConfig.Build([], null)),
            CiBuildkitConfig.Stamp(CiBuildkitConfig.Build(["reg:5000"], null)));

    // ── Snapshotter resolution ───────────────────────────────────────────────

    /// <summary>/proc/filesystems as DSM reports it: FUSE present, overlayfs absent.</summary>
    private const string DsmFilesystems = "\tfuseblk\nnodev\tfuse\nnodev\tfusectl\n\text4\n\tbtrfs\n";

    /// <summary>A typical modern host: overlayfs in the kernel.</summary>
    private const string ModernFilesystems = "nodev\toverlay\nnodev\tfuse\n\text4\n";

    /// <summary>
    /// The issue-#65 host: BuildKit's own probe would land on native, but FUSE is available —
    /// this is the one case detection must speak up in.
    /// </summary>
    [Theory]
    [InlineData(null)]
    [InlineData("auto")]
    [InlineData(" Auto ")]
    public void ResolveSnapshotter_DefaultsToFuseOverlayfsWhereTheKernelLacksOverlayfsButHasFuse(string? configured) =>
        Assert.Equal("fuse-overlayfs", CiBuildkitConfig.ResolveSnapshotter(configured, "btrfs", DsmFilesystems));

    [Fact]
    public void ResolveSnapshotter_StaysSilentWhereTheKernelHasOverlayfs() =>
        Assert.Null(CiBuildkitConfig.ResolveSnapshotter(null, "btrfs", ModernFilesystems));

    /// <summary>
    /// An overlay-family storage driver proves kernel overlayfs even when /proc/filesystems is
    /// unreadable (Watchtower on a non-Linux dev host talking to a remote engine).
    /// </summary>
    [Fact]
    public void ResolveSnapshotter_TrustsAnOverlayStorageDriverWithoutProcFilesystems() =>
        Assert.Null(CiBuildkitConfig.ResolveSnapshotter(null, "overlay2", string.Empty));

    /// <summary>Neither overlayfs nor FUSE: native is all there is, so say nothing.</summary>
    [Fact]
    public void ResolveSnapshotter_StaysSilentWhereNothingBetterExists() =>
        Assert.Null(CiBuildkitConfig.ResolveSnapshotter(null, "vfs", "\text4\n\tfuseblk\n"));

    [Fact]
    public void ResolveSnapshotter_NoneDisablesDetection() =>
        Assert.Null(CiBuildkitConfig.ResolveSnapshotter("none", "btrfs", DsmFilesystems));

    [Fact]
    public void ResolveSnapshotter_AnExplicitNameWinsOverDetection() =>
        Assert.Equal("stargz", CiBuildkitConfig.ResolveSnapshotter("stargz", "overlay2", ModernFilesystems));

    [Fact]
    public void ResolveSnapshotter_RefusesAnInvalidExplicitName() =>
        Assert.Throws<ArgumentException>(() => CiBuildkitConfig.ResolveSnapshotter("no\"quotes", "btrfs", DsmFilesystems));

    /// <summary>`fuseblk`/`fusectl` alone are not FUSE support — the token must be exactly `fuse`.</summary>
    [Fact]
    public void ResolveSnapshotter_DoesNotMistakeFuseblkForFuse() =>
        Assert.Null(CiBuildkitConfig.ResolveSnapshotter(null, "btrfs", "\tfuseblk\nnodev\tfusectl\n\tbtrfs\n"));
}
