using Watchtower.Application.Services;
using Xunit;

namespace Watchtower.Application.Tests;

/// <summary>
/// The generated buildkitd.default.toml is what every consuming repo's
/// <c>docker/setup-buildx-action</c> silently inherits, so its shape is contract: registry stanzas
/// for exactly the daemon's insecure registries, an optional snapshotter override, and nothing a
/// hostile value could turn into TOML of its own.
/// </summary>
public sealed class CiBuildkitConfigTests {

    [Fact]
    public void Build_EmitsARegistryStanzaPerInsecureRegistry() {
        var toml = CiBuildkitConfig.Build(["simondatastore:50000", "10.0.0.5:5000"], snapshotter: null);

        Assert.Contains("[registry.\"simondatastore:50000\"]\n  http = true\n  insecure = true\n", toml);
        Assert.Contains("[registry.\"10.0.0.5:5000\"]", toml);
        Assert.DoesNotContain("[worker.oci]", toml);
    }

    [Fact]
    public void Build_EmitsTheSnapshotterOverride() {
        var toml = CiBuildkitConfig.Build([], "fuse-overlayfs");

        Assert.Contains("[worker.oci]\n  snapshotter = \"fuse-overlayfs\"\n", toml);
    }

    [Fact]
    public void Build_WithNothingToConfigure_StillReturnsTheHeaderOnlyFile() {
        var toml = CiBuildkitConfig.Build([], snapshotter: null);

        // Always a file: an emptied configuration must overwrite a stale one on the volume.
        Assert.StartsWith("# Generated by Watchtower", toml);
        Assert.DoesNotContain("[", toml);
    }

    /// <summary>
    /// Registry names reach this from the daemon's own config, but a value that cannot be a
    /// registry host must not be emitted into a quoted TOML string.
    /// </summary>
    [Theory]
    [InlineData("bad\"host")]
    [InlineData("bad host")]
    [InlineData("bad\\host")]
    [InlineData("host\"]\n[worker.oci")]
    public void Build_SkipsRegistryNamesThatCannotBeHosts(string name) {
        var toml = CiBuildkitConfig.Build([name, "good:5000"], snapshotter: null);

        Assert.Contains("[registry.\"good:5000\"]", toml);
        Assert.Single(toml.Split("[registry."), s => s.StartsWith('"'));
    }

    [Fact]
    public void Build_RefusesAnInvalidSnapshotterInsteadOfEmittingBrokenToml() =>
        Assert.Throws<ArgumentException>(() => CiBuildkitConfig.Build([], "no\"quotes"));

    [Theory]
    [InlineData("native", true)]
    [InlineData("overlayfs", true)]
    [InlineData("fuse-overlayfs", true)]
    [InlineData("stargz", true)]
    [InlineData("", false)]
    [InlineData("Fuse-Overlayfs", false)]
    [InlineData("a b", false)]
    [InlineData("x\"y", false)]
    public void IsValidSnapshotter_AcceptsSnapshotterNamesOnly(string value, bool valid) =>
        Assert.Equal(valid, CiBuildkitConfig.IsValidSnapshotter(value));

    [Fact]
    public void Build_IsStableForTheSameInputsRegardlessOfOrder() {
        var a = CiBuildkitConfig.Build(["b:1", "a:1"], "native");
        var b = CiBuildkitConfig.Build(["a:1", "b:1"], "native");

        Assert.Equal(a, b);
        Assert.Equal(CiBuildkitConfig.Stamp(a), CiBuildkitConfig.Stamp(b));
    }

    [Fact]
    public void Stamp_ChangesWithTheContent() =>
        Assert.NotEqual(
            CiBuildkitConfig.Stamp(CiBuildkitConfig.Build([], null)),
            CiBuildkitConfig.Stamp(CiBuildkitConfig.Build(["reg:5000"], null)));

    // ── Snapshotter resolution ───────────────────────────────────────────────

    /// <summary>
    /// The default emits nothing — BuildKit's own probe (overlayfs, then fuse-overlayfs with a
    /// real test mount, then native) is already better evidence than anything Watchtower could
    /// detect from the outside, and an emitted name would make buildkitd skip that check.
    /// </summary>
    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("  ")]
    [InlineData("auto")]
    [InlineData(" Auto ")]
    [InlineData("none")]
    [InlineData("NONE")]
    public void ResolveSnapshotter_EmitsNothingUnlessExplicitlyNamed(string? configured) =>
        Assert.Null(CiBuildkitConfig.ResolveSnapshotter(configured));

    [Theory]
    [InlineData("fuse-overlayfs", "fuse-overlayfs")]
    [InlineData(" stargz ", "stargz")]
    [InlineData("native", "native")]
    public void ResolveSnapshotter_WritesAnExplicitNameAsIs(string configured, string expected) =>
        Assert.Equal(expected, CiBuildkitConfig.ResolveSnapshotter(configured));

    [Fact]
    public void ResolveSnapshotter_RefusesAnInvalidExplicitName() =>
        Assert.Throws<ArgumentException>(() => CiBuildkitConfig.ResolveSnapshotter("no\"quotes"));
}
