using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Watchtower.Application.Config;
using Watchtower.Application.Entities;
using Watchtower.Application.Persistence;
using Watchtower.Application.Services;
using Xunit;

namespace Watchtower.Application.Tests;

/// <summary>
/// Covers the deploy pipeline's use of the injection policy: the generated compose override, where it
/// is merged, what it says, and that it does not outlive the deploy.
/// </summary>
/// <remarks>
/// The two out-of-process steps — cloning and the compose CLI — are doubles, so what is under test is
/// the wiring between them: that <c>config</c> is read with the deploy's own env file, that the
/// override reaches <em>both</em> <c>pull</c> and <c>up</c>, that its content matches the policy, and
/// that the file carrying an App API token is gone by the end whichever way the deploy went.
/// </remarks>
public sealed class DeployEnvInjectionTests {
    private const string SingleService = """{ "services": { "app": {} } }""";

    [Fact]
    public async Task Deploy_MergesAnOverrideCarryingTheTokenIntoBothPullAndUp() {
        using var host = AuthTestHost.Start(("Watchtower:PublicBaseUrl", "https://watchtower.example.com"));
        var stackId = await host.AddStackAsync("shop");
        var compose = new RecordingComposeCliService { ConfigJson = SingleService };

        var run = await RunDeployAsync(host, stackId, compose);

        Assert.Equal("success", run.Status);
        var pull = compose.Invocation("pull");
        var up = compose.Invocation("up");

        // Both verbs carry the override as a second --file, after the repository's: compose merges
        // files in argument order, so this position is the whole reason the override wins its keys.
        foreach (var invocation in new[] { pull, up }) {
            Assert.Equal(2, invocation.ComposeFiles.Count);
            Assert.EndsWith("docker-compose.yml", invocation.ComposeFiles[0], StringComparison.Ordinal);
            Assert.StartsWith(
                "watchtower-override-", Path.GetFileName(invocation.ComposeFiles[1]), StringComparison.Ordinal);
        }
        Assert.Equal(
            ["compose", "--file", pull.ComposeFiles[0], "--file", pull.ComposeFiles[1],
             "--project-name", "shop", "--env-file", pull.EnvFilePath!, "pull"],
            pull.Args);
        Assert.Equal(
            ["compose", "--file", up.ComposeFiles[0], "--file", up.ComposeFiles[1],
             "--project-name", "shop", "--env-file", up.EnvFilePath!, "up", "-d", "--remove-orphans"],
            up.Args);
        Assert.Equal(pull.OverrideFilePath, up.OverrideFilePath);

        // The override says what the policy decided, and the token in it is the one the App API will
        // authenticate against.
        Assert.Equal(
            $"""
            # Generated by Watchtower for this deploy — not part of the repository.
            services:
              'app':
                environment:
                  'WATCHTOWER_APP_TOKEN': '{run.AppApiToken}'
                  'WATCHTOWER_STACK_ID': '{stackId}'
                  'WATCHTOWER_URL': 'https://watchtower.example.com'

            """.ReplaceLineEndings("\n"),
            pull.OverrideContent);

        // Read back with the deploy's own env file, so `config` resolves the project exactly the way
        // pull and up are about to — and from the repository's file alone, since the override is what
        // that call is being asked to produce.
        Assert.Equal(pull.EnvFilePath, compose.Invocation("config").EnvFilePath);
        Assert.NotNull(pull.EnvFilePath);
        Assert.Equal([pull.ComposeFiles[0]], compose.Invocation("config").ComposeFiles);
    }

    [Fact]
    public async Task Deploy_NamesTheInjectedVariablesInItsOutput_WithoutTheirValues() {
        using var host = AuthTestHost.Start();
        var stackId = await host.AddStackAsync("shop");
        var compose = new RecordingComposeCliService { ConfigJson = SingleService };

        var run = await RunDeployAsync(host, stackId, compose);

        Assert.Contains(
            "[Watchtower] Injecting WATCHTOWER_APP_TOKEN, WATCHTOWER_STACK_ID into service 'app'",
            run.Output);
        // The token is a credential and the deploy output is shown, streamed and stored.
        Assert.NotNull(run.AppApiToken);
        Assert.DoesNotContain(run.AppApiToken, run.Output);
    }

    [Fact]
    public async Task Deploy_WritesTheOverrideToATempFileAndDeletesItAfterwards() {
        using var host = AuthTestHost.Start();
        var stackId = await host.AddStackAsync("shop");
        var compose = new RecordingComposeCliService { ConfigJson = SingleService };

        await RunDeployAsync(host, stackId, compose);

        var overridePath = compose.Invocation("up").OverrideFilePath!;
        Assert.Equal(
            Path.TrimEndingDirectorySeparator(Path.GetTempPath()),
            Path.TrimEndingDirectorySeparator(Path.GetDirectoryName(overridePath)!));
        Assert.StartsWith("watchtower-override-", Path.GetFileName(overridePath), StringComparison.Ordinal);
        // It held the token while compose was running, and nothing is left holding it now.
        Assert.NotNull(compose.Invocation("up").OverrideContent);
        Assert.False(File.Exists(overridePath));
    }

    /// <summary>The file carries a credential, so a failed deploy must not be the case that leaves it behind.</summary>
    [Fact]
    public async Task Deploy_DeletesTheOverrideFileEvenWhenTheDeployFails() {
        using var host = AuthTestHost.Start();
        var stackId = await host.AddStackAsync("shop");
        var compose = new RecordingComposeCliService { ConfigJson = SingleService, UpExitCode = 1 };

        var run = await RunDeployAsync(host, stackId, compose);

        Assert.Equal("failed", run.Status);
        Assert.False(File.Exists(compose.Invocation("up").OverrideFilePath!));
    }

    /// <summary>
    /// The label is the opt-out for a repository that does not want the credential in that container —
    /// including the tenant target service, the one service that would otherwise get it unasked.
    /// </summary>
    [Fact]
    public async Task Deploy_LeavesTheTokenOutEntirelyWhenTheTenantTargetOptedOut() {
        using var host = AuthTestHost.Start();
        var templateId = await host.AddTemplateAsync("billing");
        var stackId = await host.AddStackAsync("billing-acme", templateId, "acme");
        var compose = new RecordingComposeCliService {
            ConfigJson = """
                {
                  "services": {
                    "web": { "labels": { "watchtower.inject-token": "false" } },
                    "worker": {}
                  }
                }
                """,
        };

        var run = await RunDeployAsync(host, stackId, compose);

        var content = compose.Invocation("up").OverrideContent!;
        Assert.DoesNotContain(AppApiTokens.TokenVariable, content);
        Assert.NotNull(run.AppApiToken);
        Assert.DoesNotContain(run.AppApiToken, content);
        // The identifying variables are unaffected — only the credential is withheld.
        Assert.Contains($"'WATCHTOWER_STACK_ID': '{stackId}'", content);
    }

    /// <summary>A tenant whose template names the target service gets it without touching its compose file.</summary>
    [Fact]
    public async Task Deploy_InjectsTheTokenIntoATenantsTargetServiceOnly() {
        using var host = AuthTestHost.Start();
        var templateId = await host.AddTemplateAsync("billing");
        var stackId = await host.AddStackAsync("billing-acme", templateId, "acme");
        var compose = new RecordingComposeCliService {
            ConfigJson = """{ "services": { "web": {}, "worker": {} } }""",
        };

        var run = await RunDeployAsync(host, stackId, compose);

        Assert.Contains($"'WATCHTOWER_APP_TOKEN': '{run.AppApiToken}'", compose.Invocation("up").OverrideContent!);
        Assert.Contains(
            "[Watchtower] Injecting WATCHTOWER_APP_TOKEN, WATCHTOWER_STACK_ID into service 'web'", run.Output);
        Assert.Contains("[Watchtower] Injecting WATCHTOWER_STACK_ID into service 'worker'", run.Output);
    }

    [Fact]
    public async Task Deploy_ReportsALabelValueItCannotUse() {
        using var host = AuthTestHost.Start();
        var stackId = await host.AddStackAsync("shop");
        var compose = new RecordingComposeCliService {
            ConfigJson = """
                { "services": { "web": { "labels": { "watchtower.inject-token": "yes" } }, "worker": {} } }
                """,
        };

        var run = await RunDeployAsync(host, stackId, compose);

        Assert.Contains(
            "[Watchtower] Warning: service 'web' has an unrecognized watchtower.inject-token value 'yes'",
            run.Output);
        Assert.DoesNotContain(AppApiTokens.TokenVariable, compose.Invocation("up").OverrideContent!);
    }

    [Fact]
    public async Task Deploy_ReportsATenantTargetServiceThatIsNotInTheComposeFile() {
        using var host = AuthTestHost.Start();
        var templateId = await host.AddTemplateAsync("billing");
        var stackId = await host.AddStackAsync("billing-acme", templateId, "acme");
        var compose = new RecordingComposeCliService {
            ConfigJson = """{ "services": { "frontend": {}, "worker": {} } }""",
        };

        var run = await RunDeployAsync(host, stackId, compose);

        Assert.Contains("[Watchtower] Warning: the template's target service 'web'", run.Output);
        Assert.Equal("success", run.Status);
        Assert.DoesNotContain(AppApiTokens.TokenVariable, compose.Invocation("up").OverrideContent!);
    }

    /// <summary>
    /// The same file is about to be handed to pull and up, so a project that cannot be read is a
    /// failure now rather than a more confusing one two steps later.
    /// </summary>
    [Fact]
    public async Task Deploy_FailsWithComposesOwnErrorWhenTheProjectCannotBeRead() {
        using var host = AuthTestHost.Start();
        var stackId = await host.AddStackAsync("shop");
        var compose = new RecordingComposeCliService {
            ConfigExitCode = 1,
            ConfigDiagnostics = "services.web.image: required attribute is missing",
        };

        var run = await RunDeployAsync(host, stackId, compose);

        Assert.Equal("failed", run.Status);
        Assert.Contains("services.web.image: required attribute is missing", run.Output);
        Assert.Equal(["config"], compose.Invocations.Select(i => i.Command));
    }

    /// <summary>
    /// A project with no services at all leaves nothing to write: an override file whose
    /// <c>services:</c> key had no entries under it would not be a valid compose file.
    /// </summary>
    [Fact]
    public async Task Deploy_PassesNoOverrideWhenTheProjectDeclaresNoServices() {
        using var host = AuthTestHost.Start();
        var stackId = await host.AddStackAsync("shop");
        var compose = new RecordingComposeCliService { ConfigJson = """{ "services": {} }""" };

        var run = await RunDeployAsync(host, stackId, compose);

        Assert.Equal("success", run.Status);
        Assert.Null(compose.Invocation("pull").OverrideFilePath);
        Assert.Null(compose.Invocation("up").OverrideFilePath);
    }

    // ── Helpers ──────────────────────────────────────────────────────────────────────────────────

    /// <summary>What one deploy left behind: its tracking row, and the token it injected.</summary>
    private sealed record DeployRun(string Status, string Output, string? AppApiToken);

    /// <summary>
    /// Runs a single deploy to completion on the calling thread.
    /// </summary>
    /// <remarks>
    /// Deliberately not through <see cref="DeployQueueService.Enqueue"/>: that starts a background
    /// worker, and waiting on it would mean polling the one SQLite connection the worker is writing
    /// through. Everything a deploy does out of process is a double, so there is nothing left to wait
    /// for anyway.
    /// </remarks>
    private static async Task<DeployRun> RunDeployAsync(
        AuthTestHost host, int stackId, RecordingComposeCliService compose) {
        var ct = TestContext.Current.CancellationToken;
        var eventId = await CreateDeployEventAsync(host, stackId);

        using (var queue = new DeployQueueService(
                   host.Services.GetRequiredService<IServiceScopeFactory>(),
                   new StubGitCloneService(),
                   compose,
                   host.Services.GetRequiredService<DockerEngineClient>(),
                   host.Services.GetRequiredService<DeployOutputBroadcaster>(),
                   host.Services.GetRequiredService<CaddyManager>(),
                   host.Services.GetRequiredService<IOptionsMonitor<WatchtowerOptions>>(),
                   NullLogger<DeployQueueService>.Instance)) {
            await queue.ExecuteDeployAsync(stackId, eventId, removeVolumes: null, ct);
        }

        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        var deployEvent = await db.DeployEvents.AsNoTracking().FirstAsync(e => e.Id == eventId, ct);
        var token = await db.Stacks.AsNoTracking()
            .Where(s => s.Id == stackId).Select(s => s.AppApiToken).FirstAsync(ct);
        return new DeployRun(deployEvent.Status, deployEvent.Output ?? string.Empty, token);
    }

    private static async Task<int> CreateDeployEventAsync(AuthTestHost host, int stackId) {
        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        var deployEvent = new DeployEvent {
            StackId = stackId, TriggeredBy = "test", Status = "queued", StartedAt = DateTimeOffset.UtcNow,
        };
        db.DeployEvents.Add(deployEvent);
        await db.SaveChangesAsync(TestContext.Current.CancellationToken);
        return deployEvent.Id;
    }
}
