using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Watchtower.Application.Config;
using Watchtower.Application.Entities;
using Watchtower.Application.Persistence;
using Watchtower.Application.Services;
using Xunit;

namespace Watchtower.Application.Tests;

/// <summary>
/// The behaviour-changing half of ADR-0026: what a deploy does once a product is in
/// <see cref="ProductReleaseMode.Releases"/>, and — the acceptance test for the whole stage — what it
/// still does when the product is in <see cref="ProductReleaseMode.Git"/>.
/// </summary>
/// <remarks>
/// Both out-of-process steps are doubles that <em>record</em>: <see cref="StubGitCloneService"/> which
/// clone form was asked for, <see cref="RecordingComposeCliService"/> the whole compose argument list
/// and the override file's content while it existed. That is what lets invariant 1 — "a product with no
/// releases deploys byte-for-byte as it did before" — be an assertion about the calls rather than a
/// claim about the code.
/// </remarks>
public sealed class ReleaseDeployTests {
    private static CancellationToken Ct => TestContext.Current.CancellationToken;

    private const string SingleService = """
        { "services": { "api": { "image": "ghcr.io/acme/api:latest" } } }
        """;

    private const string ApiAndDb = """
        {
          "services": {
            "api": { "image": "ghcr.io/acme/api:latest" },
            "db": { "image": "postgres:16" }
          }
        }
        """;

    // ── invariant 1: Git mode is untouched ───────────────────────────────────────────────────────

    /// <summary>
    /// The golden record. A product in <c>Git</c> mode clones the branch head, writes an override with
    /// no <c>image:</c> in it, stamps no release on the event and leaves the stack's release columns
    /// null — which together <em>are</em> "deploys as it did before ADR-0026".
    /// </summary>
    /// <remarks>
    /// Deliberately asserted as exact values rather than as absences: "there is no image line" would
    /// still pass if the whole override had stopped being written.
    /// </remarks>
    [Fact]
    public async Task Deploy_OfAGitModeProduct_ClonesTheBranchHeadAndPinsNothing() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop", ProductReleaseMode.Git);
        var stackId = await host.AddProductStackAsync("shop-prod", productId);
        // Releases may exist and still change nothing: the mode is the switch, not their presence.
        await host.AddReleaseAsync(productId, "v1");

        var run = await RunDeployAsync(host, stackId, ApiAndDb);

        Assert.Equal("success", run.Status);
        Assert.Equal(
            [new GitInvocation("clone", "https://example.invalid/shop.git", "main")],
            run.Clones);
        Assert.Equal(
            $"""
            # Generated by Watchtower for this deploy — not part of the repository.
            services:
              'api':
                environment:
                  'WATCHTOWER_STACK_ID': '{stackId}'
              'db':
                environment:
                  'WATCHTOWER_STACK_ID': '{stackId}'

            """.ReplaceLineEndings("\n"),
            run.Compose.Invocation("up").OverrideContent);
        Assert.DoesNotContain("Deploying release", run.Output, StringComparison.Ordinal);
        Assert.DoesNotContain("Pinning service", run.Output, StringComparison.Ordinal);
        Assert.Null(await EventReleaseAsync(host, run.EventId));
        Assert.Equal((null, null), await host.ReleaseStateAsync(stackId));
    }

    /// <summary>
    /// The mutation of the test above: the <em>only</em> thing changed is the product's mode, and every
    /// assertion that held for Git mode now fails to hold. Without this, the golden test could be
    /// passing because the release machinery never runs at all.
    /// </summary>
    [Fact]
    public async Task Deploy_OfAReleaseModeProduct_ClonesTheCommitAndPinsTheDigest() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);
        var releaseId = await host.AddReleaseAsync(productId, "v1");

        var run = await RunDeployAsync(host, stackId, ApiAndDb);

        Assert.Equal("success", run.Status);
        Assert.Equal(
            [new GitInvocation(
                "clone-at-commit", "https://example.invalid/shop.git", "main", ReleaseTestEstate.ReleaseCommit)],
            run.Clones);
        // 'db' runs postgres, which the release did not build — untouched, and no allowlist said so.
        Assert.Equal(
            $"""
            # Generated by Watchtower for this deploy — not part of the repository.
            services:
              'api':
                image: 'ghcr.io/acme/api@{ReleaseTestEstate.ApiDigest}'
                environment:
                  'WATCHTOWER_STACK_ID': '{stackId}'
              'db':
                environment:
                  'WATCHTOWER_STACK_ID': '{stackId}'

            """.ReplaceLineEndings("\n"),
            run.Compose.Invocation("up").OverrideContent);
        Assert.Contains(
            $"[Watchtower] Deploying release v1 (commit {ReleaseTestEstate.ReleaseCommit[..8]})",
            run.Output, StringComparison.Ordinal);
        Assert.Contains(
            $"[Watchtower] Pinning service 'api' to ghcr.io/acme/api@{ReleaseTestEstate.ApiDigest}",
            run.Output, StringComparison.Ordinal);
        Assert.Equal(releaseId, await EventReleaseAsync(host, run.EventId));
        Assert.Equal((null, releaseId), await host.ReleaseStateAsync(stackId));
    }

    /// <summary>
    /// A product in <c>Releases</c> mode with no releases yet is the transitional state an operator can
    /// reach by hand. The resolver answers null and the deploy falls back to the Git path rather than
    /// refusing — nothing is worse for a fleet than a mode change that stops deploys.
    /// </summary>
    [Fact]
    public async Task Deploy_OfAReleaseModeProductWithNoReleases_FallsBackToTheBranchHead() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);

        var run = await RunDeployAsync(host, stackId, SingleService);

        Assert.Equal("success", run.Status);
        Assert.Equal("clone", Assert.Single(run.Clones).Command);
        Assert.Null(await EventReleaseAsync(host, run.EventId));
    }

    // ── resolution ───────────────────────────────────────────────────────────────────────────────

    /// <summary>A pin outranks "newest": the whole point of pinning is that later releases do not move it.</summary>
    [Fact]
    public async Task Deploy_OfAPinnedStack_DeploysThePinRatherThanTheNewestRelease() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var oldId = await host.AddReleaseAsync(productId, "v1");
        await host.AddReleaseAsync(
            productId, "v2", ReleaseTestEstate.NextReleaseCommit,
            ("ghcr.io/acme/api", ReleaseTestEstate.NextApiDigest));
        var stackId = await host.AddProductStackAsync("shop-prod", productId, pinnedReleaseId: oldId);

        var run = await RunDeployAsync(host, stackId, SingleService);

        Assert.Equal(ReleaseTestEstate.ReleaseCommit, Assert.Single(run.Clones).CommitSha);
        Assert.Contains(ReleaseTestEstate.ApiDigest, run.Compose.Invocation("up").OverrideContent!, StringComparison.Ordinal);
        Assert.Equal((oldId, oldId), await host.ReleaseStateAsync(stackId));
    }

    /// <summary>
    /// Convergence (invariant 3): the deploy resolves its release when it <em>runs</em>, so a release
    /// published after the enqueue is the one that gets deployed — not the one that was newest when the
    /// work was queued.
    /// </summary>
    /// <remarks>
    /// Staged through the cross-stack gate, which is the real mechanism a fan-out drains behind: one
    /// stack holds the only permit while a second deploy — enqueued when v1 was newest — waits, and v2
    /// lands during the wait. Had the release id been captured at enqueue, the waiting deploy would
    /// still run v1; the assertion is that it runs v2.
    /// </remarks>
    [Fact]
    public async Task Deploy_ResolvesTheReleaseThatLandedWhileItWaitedAtTheGate() {
        using var host = AuthTestHost.Start(("Watchtower:MaxConcurrentDeploys", "1"));
        var productId = await host.AddProductAsync("shop");
        await host.AddReleaseAsync(productId, "v1");
        var holderId = await host.AddProductStackAsync("holder", productId);
        var waitingId = await host.AddProductStackAsync("waiting", productId);

        var probe = new ConcurrencyProbeComposeCliService { Hold = TimeSpan.FromMilliseconds(500) };
        var git = new StubGitCloneService();
        using var gateQueue = CreateQueue(host, probe, git);
        var holderEvent = await CreateDeployEventAsync(host, holderId, DeployTriggers.Release);
        var waitingEvent = await CreateDeployEventAsync(host, waitingId, DeployTriggers.Release);

        var holder = Task.Run(
            () => gateQueue.ExecuteDeployAsync(holderId, holderEvent, DeployTriggers.Release, null, Ct), Ct);
        await WaitUntilAsync(async () => await StatusOfAsync(host, holderEvent) == "running");
        var waiting = Task.Run(
            () => gateQueue.ExecuteDeployAsync(waitingId, waitingEvent, DeployTriggers.Release, null, Ct), Ct);
        await WaitUntilAsync(async () =>
            (await OutputOfAsync(host, waitingEvent)).Contains("Waiting for a deploy slot", StringComparison.Ordinal));

        // v2 is published while the second deploy is parked — exactly the "release lands mid-drain" case.
        var v2 = await host.AddReleaseAsync(
            productId, "v2", ReleaseTestEstate.NextReleaseCommit,
            ("ghcr.io/acme/api", ReleaseTestEstate.NextApiDigest));

        await Task.WhenAll(holder, waiting);

        Assert.Equal("success", await StatusOfAsync(host, waitingEvent));
        Assert.Equal(v2, await EventReleaseAsync(host, waitingEvent));
        Assert.Equal(v2, (await host.ReleaseStateAsync(waitingId)).LastDeployed);
        Assert.Contains(
            new GitInvocation(
                "clone-at-commit", "https://example.invalid/shop.git", "main",
                ReleaseTestEstate.NextReleaseCommit),
            git.Clones);
    }

    /// <summary>
    /// The same staleness rule the stopped-stack re-check follows: a pin written while the deploy sat at
    /// the gate is honoured, because the release is resolved from the stack read on the far side of it.
    /// </summary>
    [Fact]
    public async Task Deploy_HonoursAPinWrittenWhileItWaitedAtTheGate() {
        using var host = AuthTestHost.Start(("Watchtower:MaxConcurrentDeploys", "1"));
        var productId = await host.AddProductAsync("shop");
        var v1 = await host.AddReleaseAsync(productId, "v1");
        await host.AddReleaseAsync(
            productId, "v2", ReleaseTestEstate.NextReleaseCommit,
            ("ghcr.io/acme/api", ReleaseTestEstate.NextApiDigest));
        var holderId = await host.AddProductStackAsync("holder", productId);
        var waitingId = await host.AddProductStackAsync("waiting", productId);

        var probe = new ConcurrencyProbeComposeCliService { Hold = TimeSpan.FromMilliseconds(500) };
        var git = new StubGitCloneService();
        using var gateQueue = CreateQueue(host, probe, git);
        var holderEvent = await CreateDeployEventAsync(host, holderId, DeployTriggers.Manual);
        var waitingEvent = await CreateDeployEventAsync(host, waitingId, DeployTriggers.Manual);

        var holder = Task.Run(
            () => gateQueue.ExecuteDeployAsync(holderId, holderEvent, DeployTriggers.Manual, null, Ct), Ct);
        await WaitUntilAsync(async () => await StatusOfAsync(host, holderEvent) == "running");
        var waiting = Task.Run(
            () => gateQueue.ExecuteDeployAsync(waitingId, waitingEvent, DeployTriggers.Manual, null, Ct), Ct);
        await WaitUntilAsync(async () =>
            (await OutputOfAsync(host, waitingEvent)).Contains("Waiting for a deploy slot", StringComparison.Ordinal));

        // The operator pins the parked stack back to v1 while it waits.
        await host.PinAsync(waitingId, v1);
        await Task.WhenAll(holder, waiting);

        Assert.Equal(v1, await EventReleaseAsync(host, waitingEvent));
    }

    // ── the short-circuit ────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// A fan-out deploy of a stack that already converged onto the same release does nothing — no clone,
    /// no compose, and a success saying so.
    /// </summary>
    [Fact]
    public async Task Deploy_TriggeredByARelease_ShortCircuitsWhenTheStackIsAlreadyOnIt() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var releaseId = await host.AddReleaseAsync(productId, "v1");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);
        await host.SetDeployedReleaseAsync(stackId, releaseId);

        var run = await RunDeployAsync(host, stackId, SingleService, DeployTriggers.Release);

        Assert.Equal("success", run.Status);
        Assert.Contains("[Watchtower] Already on v1 — nothing to do.", run.Output, StringComparison.Ordinal);
        Assert.Empty(run.Clones);
        Assert.Empty(run.Compose.Invocations);
        // Still stamped, so the rollout view counts it as reached rather than as missing.
        Assert.Equal(releaseId, await EventReleaseAsync(host, run.EventId));
    }

    /// <summary>
    /// The other half of the same rule, and the one that matters: a manual deploy of the identical
    /// state runs the whole pipeline. A deploy converges compose, environment and configuration too, so
    /// a manual deploy that silently did nothing would be a bug report.
    /// </summary>
    [Fact]
    public async Task Deploy_TriggeredManually_RunsEvenWhenTheStackIsAlreadyOnTheRelease() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var releaseId = await host.AddReleaseAsync(productId, "v1");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);
        await host.SetDeployedReleaseAsync(stackId, releaseId);

        var run = await RunDeployAsync(host, stackId, SingleService, DeployTriggers.Manual);

        Assert.Equal("success", run.Status);
        Assert.DoesNotContain("nothing to do", run.Output, StringComparison.Ordinal);
        Assert.Single(run.Clones);
        Assert.Equal(["config", "pull", "up"], run.Compose.Invocations.Select(i => i.Command));
    }

    /// <summary>Every other trigger behaves like a manual one, including the operator's release actions.</summary>
    [Theory]
    [InlineData(DeployTriggers.Webhook)]
    [InlineData(DeployTriggers.Schedule)]
    [InlineData(DeployTriggers.ReleaseManual)]
    public async Task Deploy_NeverShortCircuitsForAnyOtherTrigger(string trigger) {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var releaseId = await host.AddReleaseAsync(productId, "v1");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);
        await host.SetDeployedReleaseAsync(stackId, releaseId);

        var run = await RunDeployAsync(host, stackId, SingleService, trigger);

        Assert.Single(run.Clones);
        Assert.Contains("up", run.Compose.Invocations.Select(i => i.Command));
    }

    /// <summary>
    /// A release-triggered deploy that a volume recreate was coalesced onto must not be swallowed: the
    /// data wipe is the request, and the release being unchanged says nothing about it.
    /// </summary>
    [Fact]
    public async Task Deploy_DoesNotShortCircuitAVolumeRecreate() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var releaseId = await host.AddReleaseAsync(productId, "v1");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);
        await host.SetDeployedReleaseAsync(stackId, releaseId);

        var run = await RunDeployAsync(
            host, stackId, SingleService, DeployTriggers.Release, removeVolumes: ["shop_data"]);

        Assert.Single(run.Clones);
        Assert.Contains("down", run.Compose.Invocations.Select(i => i.Command));
    }

    /// <summary>A newer release is not "already on it", so the fan-out deploy runs.</summary>
    [Fact]
    public async Task Deploy_TriggeredByARelease_RunsWhenTheStackIsOnAnOlderRelease() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var v1 = await host.AddReleaseAsync(productId, "v1");
        var v2 = await host.AddReleaseAsync(
            productId, "v2", ReleaseTestEstate.NextReleaseCommit,
            ("ghcr.io/acme/api", ReleaseTestEstate.NextApiDigest));
        var stackId = await host.AddProductStackAsync("shop-prod", productId);
        await host.SetDeployedReleaseAsync(stackId, v1);

        var run = await RunDeployAsync(host, stackId, SingleService, DeployTriggers.Release);

        Assert.Equal(ReleaseTestEstate.NextReleaseCommit, Assert.Single(run.Clones).CommitSha);
        Assert.Equal(v2, (await host.ReleaseStateAsync(stackId)).LastDeployed);
    }

    /// <summary>
    /// The stack fields describe the last deploy that <em>ran</em>. A short-circuited fan-out must not
    /// touch them, or every tenant of a product would show a fresh "deployed just now" after every
    /// release, whether or not anything reached it.
    /// </summary>
    [Fact]
    public async Task Deploy_ThatShortCircuits_LeavesTheStacksLastDeployFieldsAlone() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var releaseId = await host.AddReleaseAsync(productId, "v1");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);
        await host.SetDeployedReleaseAsync(stackId, releaseId);
        var deployedAt = new DateTimeOffset(2026, 8, 1, 9, 0, 0, TimeSpan.Zero);
        await SetLastDeployAsync(host, stackId, deployedAt, DeployStatus.Success);

        var run = await RunDeployAsync(host, stackId, SingleService, DeployTriggers.Release);

        Assert.Equal("success", run.Status);
        Assert.Contains("nothing to do", run.Output, StringComparison.Ordinal);
        // Untouched — not merely "still Success", but still the *same instant*.
        var (lastAt, lastStatus) = await LastDeployAsync(host, stackId);
        Assert.Equal(deployedAt, lastAt);
        Assert.Equal(DeployStatus.Success, lastStatus);
    }

    // ── coalescing must not demote the trigger ───────────────────────────────────────────────────

    /// <summary>
    /// The trigger a coalesced deploy runs under is the <em>strongest</em> of the requests that merged
    /// into it. An operator's Deploy landing on a pending fan-out must run the full pipeline: without
    /// this the button would report success having done nothing, on a stack that is on the newest
    /// release but whose compose file or environment just changed.
    /// </summary>
    [Fact]
    public async Task Enqueue_CoalescingAManualDeployOntoAPendingRelease_RunsTheFullPipeline() {
        var run = await RunCoalescedAsync(
            firstTrigger: DeployTriggers.Release,
            pendingTrigger: DeployTriggers.Release,
            coalescedTrigger: DeployTriggers.Manual);

        Assert.Equal("success", run.Status);
        Assert.DoesNotContain("nothing to do", run.Output, StringComparison.Ordinal);
        // Two deploys reached compose: the one that was running, and the coalesced pending one.
        Assert.Equal(2, run.UpCount);
    }

    /// <summary>
    /// The reverse never demotes either: a fan-out coalescing onto a pending manual keeps "manual",
    /// because a full deploy is never the wrong answer to a release arriving.
    /// </summary>
    [Fact]
    public async Task Enqueue_CoalescingAReleaseOntoAPendingManualDeploy_StillRunsTheFullPipeline() {
        var run = await RunCoalescedAsync(
            firstTrigger: DeployTriggers.Manual,
            pendingTrigger: DeployTriggers.Manual,
            coalescedTrigger: DeployTriggers.Release);

        Assert.Equal("success", run.Status);
        Assert.DoesNotContain("nothing to do", run.Output, StringComparison.Ordinal);
        Assert.Equal(2, run.UpCount);
    }

    /// <summary>
    /// …and a pure fan-out pile-up still short-circuits, which is the behaviour the promotion rule must
    /// not have destroyed: three releases in a minute must not mean three full deploys of a converged
    /// stack.
    /// </summary>
    [Fact]
    public async Task Enqueue_CoalescingAReleaseOntoAPendingRelease_StillShortCircuits() {
        var run = await RunCoalescedAsync(
            firstTrigger: DeployTriggers.Release,
            pendingTrigger: DeployTriggers.Release,
            coalescedTrigger: DeployTriggers.Release);

        Assert.Equal("success", run.Status);
        Assert.Contains("nothing to do", run.Output, StringComparison.Ordinal);
        // Only the first deploy reached compose.
        Assert.Equal(1, run.UpCount);
    }

    // ── releases without a commit ────────────────────────────────────────────────────────────────

    /// <summary>
    /// A release that records only images still pins them; only the checkout falls back to the branch
    /// head, and the output says so rather than leaving the operator to infer it.
    /// </summary>
    [Fact]
    public async Task Deploy_OfAReleaseWithoutACommit_ClonesTheBranchButStillPins() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        await host.AddReleaseAsync(productId, "v1", commitSha: null);
        var stackId = await host.AddProductStackAsync("shop-prod", productId);

        var run = await RunDeployAsync(host, stackId, SingleService);

        Assert.Equal(
            [new GitInvocation("clone", "https://example.invalid/shop.git", "main")], run.Clones);
        Assert.Contains("no commit recorded", run.Output, StringComparison.Ordinal);
        Assert.Contains(
            $"image: 'ghcr.io/acme/api@{ReleaseTestEstate.ApiDigest}'",
            run.Compose.Invocation("up").OverrideContent!, StringComparison.Ordinal);
    }

    /// <summary>
    /// A release-mode deploy that fails still reports which release it was trying to apply — the id is
    /// stamped as soon as it is resolved, not when the deploy succeeds.
    /// </summary>
    [Fact]
    public async Task Deploy_StampsTheReleaseEvenWhenItFails() {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        var releaseId = await host.AddReleaseAsync(productId, "v1");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);

        var run = await RunDeployAsync(host, stackId, SingleService, upExitCode: 1);

        Assert.Equal("failed", run.Status);
        Assert.Equal(releaseId, await EventReleaseAsync(host, run.EventId));
        // …and the stack is not recorded as being on it, because it is not.
        Assert.Null((await host.ReleaseStateAsync(stackId)).LastDeployed);
    }

    // ── Helpers ──────────────────────────────────────────────────────────────────────────────────

    /// <summary>What one deploy left behind, plus the two recorders it ran against.</summary>
    private sealed record DeployRun(
        int EventId, string Status, string Output,
        IReadOnlyList<GitInvocation> Clones, RecordingComposeCliService Compose);

    /// <summary>Runs one deploy to completion on the calling thread, as <see cref="DeployEnvInjectionTests"/> does.</summary>
    private static async Task<DeployRun> RunDeployAsync(
        AuthTestHost host, int stackId, string configJson,
        string trigger = DeployTriggers.Manual, IReadOnlyList<string>? removeVolumes = null,
        int upExitCode = 0) {
        var compose = new RecordingComposeCliService { ConfigJson = configJson, UpExitCode = upExitCode };
        var git = new StubGitCloneService();
        var eventId = await CreateDeployEventAsync(host, stackId, trigger);

        using (var queue = CreateQueue(host, compose, git))
            await queue.ExecuteDeployAsync(stackId, eventId, trigger, removeVolumes, Ct);

        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        var deployEvent = await db.DeployEvents.AsNoTracking().FirstAsync(e => e.Id == eventId, Ct);
        return new DeployRun(
            eventId, deployEvent.Status, deployEvent.Output ?? string.Empty, git.Clones, compose);
    }

    /// <summary>What the coalesced pending deploy did.</summary>
    /// <param name="UpCount">How many deploys reached <c>compose up</c> — the short-circuit's tell.</param>
    private sealed record CoalescedRun(string Status, string Output, int UpCount);

    /// <summary>
    /// Drives the three-request coalescing path through the real <see cref="DeployQueueService.Enqueue"/>:
    /// one deploy running, one pending, and a third that merges onto the pending slot.
    /// </summary>
    /// <remarks>
    /// The first deploy is held inside its <c>config</c> call, which is what makes the sequence
    /// deterministic rather than a race: <c>Enqueue</c> flips <c>IsRunning</c> synchronously under the
    /// slot lock, so with the worker parked the second call is guaranteed to become the pending slot and
    /// the third to coalesce onto it. The stack starts on no release and the first deploy puts it on the
    /// newest one, so by the time the pending deploy runs it <em>is</em> converged — which is exactly the
    /// state where the trigger decides between a full deploy and a no-op.
    /// </remarks>
    private static async Task<CoalescedRun> RunCoalescedAsync(
        string firstTrigger, string pendingTrigger, string coalescedTrigger) {
        using var host = AuthTestHost.Start();
        var productId = await host.AddProductAsync("shop");
        await host.AddReleaseAsync(productId, "v1");
        var stackId = await host.AddProductStackAsync("shop-prod", productId);

        var held = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        var compose = new RecordingComposeCliService {
            ConfigJson = SingleService,
            OnConfig = () => held.Task,
        };
        using var queue = CreateQueue(host, compose, new StubGitCloneService());

        var first = queue.Enqueue(stackId, firstTrigger);
        Assert.Equal("running", first.Status);
        var pending = queue.Enqueue(stackId, pendingTrigger);
        Assert.Equal("queued", pending.Status);
        var coalesced = queue.Enqueue(stackId, coalescedTrigger);
        // The third request produced no new row — it merged onto the pending one.
        Assert.Equal(pending.DeployEventId, coalesced.DeployEventId);

        // Let the first deploy finish; the worker then picks the pending slot up with the merged trigger.
        // Only the first deploy is gated: the hook is cleared before the second one reaches config.
        compose.OnConfig = null;
        held.SetResult();
        await WaitUntilAsync(async () => await StatusOfAsync(host, pending.DeployEventId) is "success" or "failed");
        await queue.StopAsync(Ct);

        return new CoalescedRun(
            await StatusOfAsync(host, pending.DeployEventId),
            await OutputOfAsync(host, pending.DeployEventId),
            compose.Invocations.Count(i => i.Command == "up"));
    }

    private static DeployQueueService CreateQueue(
        AuthTestHost host, ComposeCliService compose, GitCloneService git) =>
        new(host.Services.GetRequiredService<IServiceScopeFactory>(),
            git,
            compose,
            host.Services.GetRequiredService<DockerEngineClient>(),
            host.Services.GetRequiredService<DeployOutputBroadcaster>(),
            host.Services.GetRequiredService<CaddyManager>(),
            host.Services.GetRequiredService<IOptionsMonitor<WatchtowerOptions>>(),
            NullLogger<DeployQueueService>.Instance);

    private static async Task<int> CreateDeployEventAsync(AuthTestHost host, int stackId, string trigger) {
        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        var deployEvent = new DeployEvent {
            StackId = stackId, TriggeredBy = trigger, Status = "queued", StartedAt = DateTimeOffset.UtcNow,
        };
        db.DeployEvents.Add(deployEvent);
        await db.SaveChangesAsync(Ct);
        return deployEvent.Id;
    }

    private static async Task<int?> EventReleaseAsync(AuthTestHost host, int eventId) {
        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        return await db.DeployEvents.AsNoTracking()
            .Where(e => e.Id == eventId).Select(e => e.ReleaseId).FirstAsync(Ct);
    }

    /// <summary>Backdates the stack's last-deploy fields, so "untouched" is checkable.</summary>
    private static async Task SetLastDeployAsync(
        AuthTestHost host, int stackId, DateTimeOffset at, DeployStatus status) {
        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        await db.Stacks.Where(s => s.Id == stackId)
            .ExecuteUpdateAsync(
                s => s.SetProperty(x => x.LastDeployedAt, at).SetProperty(x => x.LastDeployStatus, status),
                Ct);
    }

    private static async Task<(DateTimeOffset? At, DeployStatus? Status)> LastDeployAsync(
        AuthTestHost host, int stackId) {
        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        var row = await db.Stacks.AsNoTracking()
            .Where(s => s.Id == stackId)
            .Select(s => new { s.LastDeployedAt, s.LastDeployStatus })
            .FirstAsync(Ct);
        return (row.LastDeployedAt, row.LastDeployStatus);
    }

    private static async Task<string> StatusOfAsync(AuthTestHost host, int eventId) {
        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        return await db.DeployEvents.AsNoTracking()
            .Where(e => e.Id == eventId).Select(e => e.Status).FirstAsync(Ct);
    }

    private static async Task<string> OutputOfAsync(AuthTestHost host, int eventId) {
        await using var scope = host.Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WatchtowerDbContext>();
        return await db.DeployEvents.AsNoTracking()
            .Where(e => e.Id == eventId).Select(e => e.Output).FirstAsync(Ct) ?? string.Empty;
    }

    private static async Task WaitUntilAsync(Func<Task<bool>> condition) {
        var deadline = DateTimeOffset.UtcNow.AddSeconds(30);
        while (DateTimeOffset.UtcNow < deadline) {
            if (await condition()) return;
            await Task.Delay(20, Ct);
        }
        Assert.Fail("The condition was still not true after 30 seconds.");
    }
}
