<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- xunit.v3 test projects are self-executing test hosts. -->
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Watchtower.Application\Watchtower.Application.csproj" />
  </ItemGroup>

</Project>
